config/routes.rb
Rails.application.routes.draw do
  resources :bots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot.rb
class Bot < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_action :set_bot, only: [:show, :edit, :update, :destroy]

  # GET /bots
  # GET /bots.json
  def index
    @bots = Bot.all
  end

  # GET /bots/1
  # GET /bots/1.json
  def show
    graph = Koala::Facebook::API.new(@bot.page_access_token)

    @profile = graph.get_object("me")
    @messenger_profile = graph.get_object("me/messenger_profile?fields=greeting,get_started,persistent_menu")


  end

  # GET /bots/new
  def new
    @bot = Bot.new
  end

  # GET /bots/1/edit
  def edit
  end

  # POST /bots
  # POST /bots.json
  def create
    @bot = Bot.new(bot_params)

    respond_to do |format|
      if @bot.save
        format.html { redirect_to @bot, notice: 'Bot was successfully created.' }
        format.json { render :show, status: :created, location: @bot }
      else
        format.html { render :new }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bots/1
  # PATCH/PUT /bots/1.json
  def update
    respond_to do |format|
      if @bot.update(bot_params)
        format.html { redirect_to @bot, notice: 'Bot was successfully updated.' }
        format.json { render :show, status: :ok, location: @bot }
      else
        format.html { render :edit }
        format.json { render json: @bot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bots/1
  # DELETE /bots/1.json
  def destroy
    @bot.destroy
    respond_to do |format|
      format.html { redirect_to bots_url, notice: 'Bot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bot
      @bot = Bot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bot_params
      params.require(:bot).permit(:page_access_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bots_helper.rb
module BotsHelper
end

app/views/bots/_form.html.erb
<%= form_for(bot) do |f| %>
  <% if bot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bot.errors.count, "error") %> prohibited this bot from being saved:</h2>

      <ul>
      <% bot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_access_token %>
    <%= f.text_field :page_access_token %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bots/edit.html.erb
<h1>Editing Bot</h1>

<%= render 'form', bot: @bot %>

<%= link_to 'Show', @bot %> |
<%= link_to 'Back', bots_path %>

app/views/bots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bots</h1>

<table>
  <thead>
    <tr>
      <th>Page access token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bots.each do |bot| %>
      <tr>
        <td><%= bot.page_access_token %></td>
        <td><%= link_to 'Show', bot %></td>
        <td><%= link_to 'Edit', edit_bot_path(bot) %></td>
        <td><%= link_to 'Destroy', bot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bot', new_bot_path %>

app/views/bots/new.html.erb
<h1>New Bot</h1>

<%= render 'form', bot: @bot %>

<%= link_to 'Back', bots_path %>

app/views/bots/show.html.erb
<%= @profile["name"] %>

<%= @messenger_profile.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookBotManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>